### ISSUE TITLE
Animation scripting and In-Game editor

### ISSUE THREAD

**Issue by Victorious3** [Nightfall/Instrumentality#5]
In order to compete with Custom Steve, those two are mandatory.
As a follow up to a discussion on IRC, I will sum op the basic points:
1. Everything is backed by java
2. Scripting is done with Lua or a similar scripting language that wraps 1
3. The in game editor will support a basic interpolation based animation system that outputs the files of 2. In order to distinct between scripted animations (that would have to be converted to interpolation based), the animation file would be marked as being scripted, and thus allow closures as parameters

An implementation could look like this:

``` lua
animation "anim_1" {
    sequence {
       bone("arm_l"):rotate(0, 210, 0),
       bone("arm_r"):rotate(0, -210, 0)
    }:interpolation(linear):during(20),
    bone("leg_l"):rotate(10, -10, 10),
}:repeat(10)
```

A scripted animation would be declared like this:

``` lua
animation_closure "anim_2" {
    function ()
        local y = rotation()
        bone("arm_l"):rotate(0, y)
    end
}:repeat(5)
```

**Comment by ghost** [comment]
Question: why "." and not ":"?

**Comment by Victorious3** [comment]
Yeah, right...
(Fixed)

**Comment by ghost** [comment]
Also, .interpolation(linear).during(20) doesn't make that much sense...
Maybe .interpolation(linear,20)?

**Comment by Victorious3** [comment]
@gamemanj I like chaining, since you could specify a parameter like this: 
``:interpolation(linear):during(10, seconds)`

**Comment by ghost** [comment]
I've added a GUI system, adding a way to get to the editor would involve adding a tab list where the modelchooser is now (for switching between various sub-editors & the model chooser)

**Comment by ghost** [comment]
I've worked out a new plan.
The user should make poses for that particular model, and we interpolate between them.
For things like 2 poses at once, we allow a pose to be parented to another pose.
This only applies rotations on the parent pose once, no matter how many of the sub-poses are active.
This means that the bone movements required for the "idle" pose aren't repeated(which would, in the normal case, send the bones clipping into the body).
For LR/UD control, we strength-modify separate poses for each of them.
For -45 degrees, we'd use a "lookleft, 33%". (or something along those lines)
We should keep the transform numbers visible so the user can ensure they are _exactly_ opposite.

The advantage to this is that it means we can keep the playercontrol code common, and using poses instead of a full animation editor keeps things simple.
EDIT: Possible disadvantage: It means the system's also less flexible.

**Comment by ghost** [comment]
Well, though animation _scripting_ isn't a thing yet, it can be modified for different models.

**Comment by ghost** [comment]
Keyframe animation is implemented, though incomplete. Still no scripting, though.

**Comment by Victorious3** [comment]
I don't know if scripting is really necessary after all of this... Keyframe animations should do, maybe with the addition of allowing to pick the interpolation method so that you can do sine or square waves, for example. I think blender has something similar to this have to check, although it _does_ allow you to script via its python interface... Its not really used for animation though.
